### ISSUE TITLE
Unresponsive Task

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#105]
The task controlling the Backtesting Session in the Tests & Live Trades task manager was working well. I added a second process instance to the trading bot instance, and set it up with a new backtesting session. The new session is linked to a definition that is different than the one to which the first backtesting session is linked.

The task is now unresponsive: when I click Run Task in the menu, nothing happens, and the following error is logged at the browsers console:

![image](https://user-images.githubusercontent.com/13994516/69881120-5102fc80-12cc-11ea-9605-43e336b24e88.png)

The current workspace:

[Backup - Workspace - Workspace SMA - EMA - MACD - PARTIAL RSI - BRR - WHB (5).txt](https://github.com/Superalgos/DesktopApp/files/3905912/Backup.-.Workspace.-.Workspace.SMA.-.EMA.-.MACD.-.PARTIAL.RSI.-.BRR.-.WHB.5.txt)

Hit CTRL + ALT + B to go to the task in question.

**Comment by Luis-Fernando-Molina** [comment]
As the error says, there was an unexpected token on a JSON string.

![image](https://user-images.githubusercontent.com/9479367/69897487-12f9ed00-134d-11ea-916a-12545a6bd5ee.png)

If you follow the first link you end up here:

![image](https://user-images.githubusercontent.com/9479367/69897498-2e64f800-134d-11ea-8ed5-562d2d724fdd.png)

The Slippage object at the trading system level of each definition were ok, but at the Session level was not.

![image](https://user-images.githubusercontent.com/9479367/69897512-5ce2d300-134d-11ea-82e5-8594bea118fb.png)

![image](https://user-images.githubusercontent.com/9479367/69897521-74ba5700-134d-11ea-8887-e78764c37801.png)

**Comment by Luis-Fernando-Molina** [comment]
After that, only one of the processes started, checking the console log we find the reason for one of them not doing it:

![image](https://user-images.githubusercontent.com/9479367/69897706-e2678280-134f-11ea-9d11-490b65314e8f.png)

**Comment by Luis-Fernando-Molina** [comment]
Uncollapsing the AATeam where JASON bot is defined, we can see which one is:

![image](https://user-images.githubusercontent.com/9479367/69897737-42f6bf80-1350-11ea-967c-d3b2a03d9951.png)

**Comment by Luis-Fernando-Molina** [comment]
After establishing the reference parent, both backrest session can be run at the same time.

![image](https://user-images.githubusercontent.com/9479367/69897978-45a6e400-1353-11ea-82ea-6dda91015308.png)
