### ISSUE TITLE
Output Dataset looses link

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#109]
The output datasets on both daily and market MACD processes lose the link with the corresponding datasets in each of the products.

You will notice the market process output has 4 output datasets. Only the first one is properly linked. The other 3 lost the link.

The daily process output has only one output data set because I deleted the other three. Try creating an output dataset and link it to a dataset definition in one of the products, and you will see that as soon as the link is established, the output dataset becomes corrupted and you can no longer access the menu options. The link disappears probably after refreshing the page.

Workspace: 
[Backup - Workspace - Workspace SMA - EMA - MACD - PARTIAL RSI - BRR - WHB (11).txt](https://github.com/Superalgos/DesktopApp/files/3907114/Backup.-.Workspace.-.Workspace.SMA.-.EMA.-.MACD.-.PARTIAL.RSI.-.BRR.-.WHB.11.txt)

**Comment by Luis-Fernando-Molina** [comment]
Fixed
