### ISSUE TITLE
Condition not validating properly

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#113]
Conditions that used to validate properly do not any more. To isolate the issue, I created a new condition #5 on the Trigger On event of WHB:

```
chart.at01hs.bollingerSubChannel.slope != "Extreme"
```

![image](https://user-images.githubusercontent.com/13994516/69915715-7cafef00-1452-11ea-8b4a-b4b2fbfa3946.png)

The condition should be true at the candle in the above image, and it is not.

Another condition that should validate true (but doesn't) in the same candle is Condition #3 of the Take Position event:

```
chart.at02hs.bollingerChannel.direction === "Down"
```
I see simulation files are created, apparently in a proper manner. It is easy to reproduce. Simply run the simulation as it is set up and go a check the date in the image.

[Backup - Workspace - Workspace SMA - EMA - MACD - RSI - BRR - WHB (2).txt](https://github.com/Superalgos/DesktopApp/files/3908319/Backup.-.Workspace.-.Workspace.SMA.-.EMA.-.MACD.-.RSI.-.BRR.-.WHB.2.txt)

**Comment by Luis-Fernando-Molina** [comment]
The workspace lost changes done to remove Standard Channels and that was the reason this was not working well. In the last version of the workspace (repaired) this is working again.
