### ISSUE TITLE
Simulation metrics reset

### ISSUE THREAD

**Issue by matbenitez** [Superalgos/DesktopApp#12]
When running the simulation on the past, the metrics are reset on the last day:

![image](https://user-images.githubusercontent.com/34651529/63265897-06053200-c265-11e9-8c0c-ff2af45aa27f.png)

![image](https://user-images.githubusercontent.com/34651529/63265921-16b5a800-c265-11e9-9363-a885ffcafd4e.png)

Steps to reproduce are simple running a Simulation and checking at the latest day change.

**Comment by Luis-Fernando-Molina** [comment]
Check if this was solved or not with the latest patch / release

**Comment by Luis-Fernando-Molina** [comment]
@matbenitez is this still happening?
