### ISSUE TITLE
Error closing position

### ISSUE THREAD

**Issue by matbenitez** [Superalgos/DesktopApp#14]
There was an error closing the position:

![image](https://user-images.githubusercontent.com/34651529/63344537-0b2ab580-c327-11e9-9c20-dd3f8b16d6fe.png)

![image](https://user-images.githubusercontent.com/34651529/63344497-f6e6b880-c326-11e9-9032-3ce8dd698319.png)

**Comment by Luis-Fernando-Molina** [comment]
Fixed on release 3
