### ISSUE TITLE
Simulation And Live Trading

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/DesktopApp#16]
It's necessary to have the possibility to continue doing Simulations while Superalgos is running in Live Trading mode.

**Comment by Luis-Fernando-Molina** [comment]
For that you need to set up a second environment, which equals to duplication your installation in a second folder. 

After that you will need to change the VIRTUAL_PORT variable at the .ENV file located at the WebServer folder for a number of your choice between 10k and 50k.

That same number you need to put it at this line of the index.html file at the WebServer folder:

```
          urlPrefix: 'http://localhost:9999/'
```
