### ISSUE TITLE
stopLossPhase === x evaluates true only when switching phases to phase x

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#17]
If I use ```stopLossPhase === 2``` in a condition, the condition evaluates true only on the candle that Stop switches phases from 1 to 2. After the switch, the condition evaluates false, even when phase 2 is active.

The gif below shows this in practice; look at condition #3:

![test](https://user-images.githubusercontent.com/13994516/63634468-18151500-c657-11e9-9f4d-3bdf2ceed10f.gif)

**Comment by Luis-Fernando-Molina** [comment]
fixed
