### ISSUE TITLE
Innacurate initial balances at no-trades live run

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#18]
I started a Live Trading run, and balances may be showing information from a previous simulation run. See image below... there are no trades, and balanceAssetB should start with 10 USDT.

![image](https://user-images.githubusercontent.com/13994516/63634510-bdc88400-c657-11e9-8344-829705710499.png)

**Comment by Luis-Fernando-Molina** [comment]
where the layers auto refreshed?

**Comment by Luis-Fernando-Molina** [comment]
@julian-molina is this issue still happening?
