### ISSUE TITLE
Trades Simulation Layer

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#19]
The image below shows how information is plotted below each trade:

![image](https://user-images.githubusercontent.com/13994516/63636461-f1afa380-c66f-11e9-9f9b-7393c5727951.png)

In my view, it is not necessary to indicate TP or STOP as the reason for the exit, as that can be seen on the charts already.

If it needs to be there, it should be labeled to avoid confusion with the number indicating ROI. In such case, we should have:
```
Exit: TP (or STOP)
ROI: -0.32
```
If we get rid of TP or STOP, then the number for ROI is self-explanatory and wouldn't require a label. In such case, we would simply have:
```
-0.32
```
Also, the information disappears when the bar is pulled upwards, and in smaller screens may not even show.

![test](https://user-images.githubusercontent.com/13994516/63636757-ececee80-c673-11e9-91fa-9070fe5225e7.gif)

It would work best if we had the ROI number in a fixed vertical position instead of variable according to each trade. The ideal position may be above the horizontal lines marking the triggered strategies... always at the bottom of the screen.

**Comment by Luis-Fernando-Molina** [comment]
> Also, the information disappears when the bar is pulled upwards, and in smaller screens may not even show.

This is by design to avoid overlaps.

Improvement made and available in next patch
