### ISSUE TITLE
Data from previous simulation in same time period is not deleted when new simulation is run

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#23]
I run a simulation on 15 minutes with the following date range:

```
{
"initialDatetime": "2019-04-01T00:00:00.000Z"
}
```

After sometime, I go to the begining of the range, refresh simulation layers and get the following:

![image](https://user-images.githubusercontent.com/13994516/64473855-66a0d400-d16c-11e9-9a98-118445ada1cb.png)

As you can see, trades are plotted from the beginning of the range and onward. However, the Simulation panel shows a count of trades prior to the first trade in the range.

I refreshed the layers again some time later, and got the following:

![image](https://user-images.githubusercontent.com/13994516/64473892-e2028580-d16c-11e9-8ad8-cb5e1a36aa3d.png)

What I believe I'm seeing is the trades from a previous simulation. Before simulating from April 1st, I had started a simulation with the following date range:

```
{
"initialDatetime": "2019-01-01T00:00:00.000Z"
}
```

I had cut that simulation short by running the one with date at April 1st described in the beginning of this issue.

Logs from the first simulation starting at JAN 1st:

[D.2019.09.07.T.10.12.14.zip](https://github.com/Superalgos/DesktopApp/files/3586523/D.2019.09.07.T.10.12.14.zip)

Logs from the second simulation starting APR 1st:

[D.2019.09.07.T.10.13.38.zip](https://github.com/Superalgos/DesktopApp/files/3586527/D.2019.09.07.T.10.13.38.zip)

As seen in the image below, there is data from JAN 1st and onward:

![image](https://user-images.githubusercontent.com/13994516/64474018-3f4b0680-d16e-11e9-90b2-56a96266200f.png)

Adding to the confusion, if I refresh layers once again, previous trades disappear, yet the panel still accounts for them:

![image](https://user-images.githubusercontent.com/13994516/64474032-9d77e980-d16e-11e9-9ea9-d060fad30f6f.png)

**Comment by Luis-Fernando-Molina** [comment]
This should be fixed on the latest version
