### ISSUE TITLE
The button STOP BACKTESTING does not work in 1hr period.

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#33]
Clicking the button does nothing. In teh console the process can be seen processing the simulation data and not stopping.

**Comment by julian-molina** [comment]
Stopping the TASK from the Task Manager does not work either when it's calculating. It doesn't stop.

**Comment by julian-molina** [comment]
Closing the browser does not work either. All other tasks are stopped but not Jason, when it's calculating.

**Comment by Luis-Fernando-Molina** [comment]
fixed
