### ISSUE TITLE
Error while trying to drop Workspace

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#38]
On a new installation in a VM, first time running, I got the following error while trying to drop a workspace (tried different ones) on the Designer:

![image](https://user-images.githubusercontent.com/13994516/65790884-d0574100-e160-11e9-8024-945f11d416f6.png)

I then created a Trading System and a Strategy just to see if that was working. It did, but when I tried to delete them, the deletion would be broken, deleting only some of the elements, leaving some random elements hanging.

![image](https://user-images.githubusercontent.com/13994516/65790865-c7666f80-e160-11e9-9133-4055ffc48f67.png)

**Comment by julian-molina** [comment]
The issue didn't happen again when reopening the app after closing it.

**Comment by Luis-Fernando-Molina** [comment]
@julian-molina is this still happening?

**Comment by julian-molina** [comment]
I haven't seen it happen again.
