### ISSUE TITLE
VM02 Live Trading Run Report

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#40]
The screen with layers refreshed, after the weekend:

![image](https://user-images.githubusercontent.com/13994516/65859471-922c6e00-e368-11e9-8b9c-a47a61f387b5.png)

Jason seems to be running, but Olivia seems to have stopped.

Olivia market seems to show a similar error as in VM01, this time at 2019-09-29T01:46:14.081Z:

[Olivia-market.zip](https://github.com/Superalgos/DesktopApp/files/3669472/Olivia-market.zip)

Olivia daily stopped at 2019-09-29T07:26:03.222Z, no errors:

[Olivia-daily-Loop.00002467.0000.txt](https://github.com/Superalgos/DesktopApp/files/3669488/Olivia-daily-Loop.00002467.0000.txt)

No errors were found on the rest of the processes...

**Comment by Luis-Fernando-Molina** [comment]
Fix submitted for testing
