### ISSUE TITLE
Jason Execution.Context.Live.1.json, File does not exist.

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#41]
Error while trading live:

[Jason-D.2019.09.30.T.08.12.01.zip](https://github.com/Superalgos/DesktopApp/files/3670429/Jason-D.2019.09.30.T.08.12.01.zip)

I see that this folder structure doesn't exists:

![image](https://user-images.githubusercontent.com/13994516/65871402-9bc0d080-e37e-11e9-9b98-f2c696bd519d.png)

![image](https://user-images.githubusercontent.com/13994516/65871427-a8ddbf80-e37e-11e9-8843-097dbc19f0dd.png)

**Comment by Luis-Fernando-Molina** [comment]
To reconstruct what was going on when the problem happened, I would also need the previous files read marked here:

![image](https://user-images.githubusercontent.com/9479367/65901550-ba43bd80-e3b8-11e9-870f-11aedeee75f2.png)
