### ISSUE TITLE
Jason - Nonce must be greater than

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#43]
Execution stopped at 2019-10-01T04:09:15.579Z

Jason data and log files below:

[AAJason.1.0-Data.zip](https://github.com/Superalgos/DesktopApp/files/3675187/AAJason.1.0-Data.zip)

[AAJason.1.0-Logs.zip](https://github.com/Superalgos/DesktopApp/files/3675193/AAJason.1.0-Logs.zip)

**Comment by Luis-Fernando-Molina** [comment]
Each JASON process, needs to have one exchange key different to other JASON processes.
