### ISSUE TITLE
Paula, Tom and Chris didn't start in October

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#44]
As seen in the data folder structure, they didn't start work on October:

![image](https://user-images.githubusercontent.com/13994516/65947109-daff2800-e437-11e9-88bc-7ad704f64455.png)

Logs:
[AAChris.1.0-Logs.zip](https://github.com/Superalgos/DesktopApp/files/3675246/AAChris.1.0-Logs.zip)

[AATom.1.0-Tom.zip](https://github.com/Superalgos/DesktopApp/files/3675231/AATom.1.0-Tom.zip)

[AAPaula.1.0-Logs.zip](https://github.com/Superalgos/DesktopApp/files/3675225/AAPaula.1.0-Logs.zip)

**Comment by Luis-Fernando-Molina** [comment]
Paula depends on Chris which depends on Olivia. Tom also depends on Olivia. I need to have the logs of Olivia to know what happened.

**Comment by julian-molina** [comment]
Olivia was working well, as well as Bruce. Candles where up to date on all periods, showing on the charts. The logs are no longer available.
