### ISSUE TITLE
Bruce ERR createTextFile 

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#45]
Logs and data files:

[AABruce.1.0-Data.zip](https://github.com/Superalgos/DesktopApp/files/3675298/AABruce.1.0-Data.zip)

[AABruce.1.0-Logs.zip](https://github.com/Superalgos/DesktopApp/files/3675310/AABruce.1.0-Logs.zip)

**Comment by Luis-Fernando-Molina** [comment]
Possibly fixed with latest patch
