### ISSUE TITLE
Live trading layer doesn't turn on

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#46]
Errors on Browser

![image](https://user-images.githubusercontent.com/13994516/65949018-af7e3c80-e43b-11e9-8e6c-c1929d7bf23f.png)

Jason logs and data:

[AAJason.1.0-Data.zip](https://github.com/Superalgos/DesktopApp/files/3675687/AAJason.1.0-Data.zip)

[AAJason.1.0-Logs.zip](https://github.com/Superalgos/DesktopApp/files/3675694/AAJason.1.0-Logs.zip)

**Comment by julian-molina** [comment]
I deleted Jason's data to be able to start over the execution.

**Comment by Luis-Fernando-Molina** [comment]
How do you reproduce this behavior?

**Comment by julian-molina** [comment]
I don't know. It happened at the moment of launching a new version of the app.
