### ISSUE TITLE
Jason / Paula File does not exist

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#47]
Symptoms: Jason stopped. Log indicates it can't find a file from Paula.

Jason logs and data:

[AAJason.1.0-Logs.zip](https://github.com/Superalgos/DesktopApp/files/3676682/AAJason.1.0-Logs.zip)

[AAJason.1.0-Data.zip](https://github.com/Superalgos/DesktopApp/files/3676692/AAJason.1.0-Data.zip)

It seems to me that Paula's file is there but may be corrupt.

Paula data and logs:

[Paula-Bollinger-Standard-Channels-Multi-Period-Market.zip](https://github.com/Superalgos/DesktopApp/files/3676732/Paula-Bollinger-Standard-Channels-Multi-Period-Market.zip)

[AAPaula.1.0-Logs.zip](https://github.com/Superalgos/DesktopApp/files/3676761/AAPaula.1.0-Logs.zip)

I don't see any errors in Paula's logs at the time f Jason's error.

Just in case, Olivia's logs:

[AAOlivia.1.0-Logs.zip](https://github.com/Superalgos/DesktopApp/files/3676776/AAOlivia.1.0-Logs.zip)

**Comment by Luis-Fernando-Molina** [comment]
Fixed
