### ISSUE TITLE
Bring live trading layer to the foreground

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#48]
The orange circles seem to be painted behind the candles, which makes it hard to see / find them, particularly right after starting the Live Trading run, when there are few circles... It would be good if they where drawn on top of the candles, and not behind them... Maybe it's not behind and it's simply that the contrast between the orange of the circles and the red of candles is not noticeable. Yellow as in the current candle may work better...

![image](https://user-images.githubusercontent.com/13994516/65977993-2b47ab80-e473-11e9-8c21-0aac8839f40f.png)

**Comment by Luis-Fernando-Molina** [comment]
Behind or after, as of today, depends on the order in which each layer was turned off.  If you want that one in particular to be on top, turn it on after all the others.
