### ISSUE TITLE
Trade cut short in simulation

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#49]
Running a simulation on the 30 mins time period, the symptom is a trade being cut short, before price tags stop or TP:

![image](https://user-images.githubusercontent.com/13994516/66045933-f562ff80-e524-11e9-981e-a8e2da3c2ae7.png)

The workspace:

[Share - Workspace - Weak-hands buster - BTC - 1hr (5).txt](https://github.com/Superalgos/DesktopApp/files/3681176/Share.-.Workspace.-.Weak-hands.buster.-.BTC.-.1hr.5.txt)

All logs:

[Log-Files.zip](https://github.com/Superalgos/DesktopApp/files/3681181/Log-Files.zip)

Jason data:

[AAJason.1.0.zip](https://github.com/Superalgos/DesktopApp/files/3681183/AAJason.1.0.zip)

A second test on month 7 has similar issues:

![image](https://user-images.githubusercontent.com/13994516/66046660-84244c00-e526-11e9-9fdf-fa535c27380c.png)

**Comment by Luis-Fernando-Molina** [comment]
Fixed in next release
