### ISSUE TITLE
Holes in Channels and SubChannels on daily files

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#50]
10 minutes time period, Jan 1st 2019, from 19:50 to 23:50:

![image](https://user-images.githubusercontent.com/13994516/66253342-29c5fe00-e767-11e9-9fd4-fd6ccad0f42a.png)

15 minutes, same period:

![image](https://user-images.githubusercontent.com/13994516/66253360-698ce580-e767-11e9-9dde-df888b9194b6.png)

20 minutes, the hole starts at 20:40 up to midnight:

![image](https://user-images.githubusercontent.com/13994516/66253376-950fd000-e767-11e9-95d7-cd02775c442d.png)

30 minutes, from 23:00 up to midnight:

![image](https://user-images.githubusercontent.com/13994516/66253383-ba9cd980-e767-11e9-9a63-62041ee4933c.png)

40 minutes the hole expands from 22:40 to Jan 2nd at midnight:

![image](https://user-images.githubusercontent.com/13994516/66253389-eae47800-e767-11e9-9789-c84497a879fe.png)

45 minutes is similar to 40.

![image](https://user-images.githubusercontent.com/13994516/66253391-fc2d8480-e767-11e9-8ab7-75b5fbdc4d5f.png)

Sub channels are affected on the same places, with slightly different times...

**Comment by Luis-Fernando-Molina** [comment]
Fixed in next data release
