### ISSUE TITLE
UI disconnects from processes coming back from Sleep Mode

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#51]
Symptoms:

The Designer shows no sign of processes running, but some processes can be seen running on the console.

Clicking Start All Tasks or Stop all Tasks has no effect.

Closing the browser does not trigger the shutting down of processes.

**Comment by Luis-Fernando-Molina** [comment]
any known way of reproducing this?

**Comment by Luis-Fernando-Molina** [comment]
fixed
