### ISSUE TITLE
Trade cut short in simulation 2

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#56]
The symptom: the trade is cut without tagging the stop or take profit, and counted as a fail i the panel.

![image](https://user-images.githubusercontent.com/13994516/66339745-102ddd80-e944-11e9-990c-c41724539089.png)

Data:

[AAJason.1.0.zip](https://github.com/Superalgos/DesktopApp/files/3698984/AAJason.1.0.zip)

Logs:

[AAJason.1.0.zip](https://github.com/Superalgos/DesktopApp/files/3698988/AAJason.1.0.zip)

Workspace:

[Share - Workspace - BB Pong - BTC - 10 min.txt](https://github.com/Superalgos/DesktopApp/files/3699007/Share.-.Workspace.-.BB.Pong.-.BTC.-.10.min.txt)

Errors in the Designer:

This is the base asset at the Trading System level:

![image](https://user-images.githubusercontent.com/13994516/66340064-b8dc3d00-e944-11e9-90d3-29e3587e2ddb.png)

The code of the Base Asset parameter:
```
{ 
"name": "BTC",
"initialBalance": 0.1,
"minimumBalance": 0.0001,
"maximumBalance": 10
}
```

The code of the Base Asset parameter at the Backtesting Session level:

```
{ 
"name": "BTC",
"initialBalance": 0.001,
"minimumBalance": 0.0001,
"maximumBalance": 1
}
```

**Comment by julian-molina** [comment]
Also in this context, there is another situation that needs to be investigated:

![image](https://user-images.githubusercontent.com/13994516/66341935-86344380-e948-11e9-9b81-b216180625e3.png)

In the above trade, BTC is sold for 2.97 USDT. The trade fails, loosing 2.55%, however, the remaining BTC balance after the trade is 0 and the Trading System says the minimum balance has been hit. If you look at the code of both Asset Balances the minimum is 0.0001. The math doesn't add up. 2.97 / 6029 (the stop price) is 0.00049 BTC, which is still above the minimum balance.

**Comment by Luis-Fernando-Molina** [comment]
Fixed at next release
