### ISSUE TITLE
onFileCreated -> err = undefined

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#61]
I have a task with four processes. I run the task and started a backtest in one of the processes only.

First symptom, the browser lost the connection with the processes:

![image](https://user-images.githubusercontent.com/13994516/66736137-af813200-ee68-11e9-81f5-9a88c2bdbf0c.png)

Second, the console shows three processes waiting and the error in the subject of the issue:

![image](https://user-images.githubusercontent.com/13994516/66735612-1e5d8b80-ee67-11e9-9f76-dbe18d569014.png)

The logs show that one of the processes waiting is not logging, while the other three are producing logs:

![image](https://user-images.githubusercontent.com/13994516/66736223-e5261b00-ee68-11e9-91a2-be3ef096fc7c.png)

Logs:

[AAJason.1.0.zip](https://github.com/Superalgos/DesktopApp/files/3723477/AAJason.1.0.zip)

Data:

[AAJason.1.0.zip](https://github.com/Superalgos/DesktopApp/files/3723480/AAJason.1.0.zip)

Workspace:

[Share - Workspace - BB Pong - BTC - 10 min (2).txt](https://github.com/Superalgos/DesktopApp/files/3723486/Share.-.Workspace.-.BB.Pong.-.BTC.-.10.min.2.txt)

**Comment by julian-molina** [comment]
I happened again today, same version of the app, while running two backtests simultaneously. Details follow:

Workspace:

[Share - Workspace - BB Pong - BTC - 10 min (3).txt](https://github.com/Superalgos/DesktopApp/files/3728949/Share.-.Workspace.-.BB.Pong.-.BTC.-.10.min.3.txt)

Logs:

[AAJason.1.0.zip](https://github.com/Superalgos/DesktopApp/files/3728954/AAJason.1.0.zip)

Data:

[7a681e8d-7167-4edb-bb2f-90e12c7f5418.zip](https://github.com/Superalgos/DesktopApp/files/3729002/7a681e8d-7167-4edb-bb2f-90e12c7f5418.zip)

[715839bb-a76c-427f-a48f-5bf1b2184070.zip](https://github.com/Superalgos/DesktopApp/files/3729012/715839bb-a76c-427f-a48f-5bf1b2184070.zip)

**Comment by Luis-Fernando-Molina** [comment]
Fiexed
