### ISSUE TITLE
Charts going nuts

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#64]
A strange case of renderings on the charts going erratic. After using the app for a full day, many backtests and with many simulations open in the charts, I got the situation shown in the GIF below.

![test](https://user-images.githubusercontent.com/13994516/66812599-811c5900-ef33-11e9-8f85-5d949b470320.gif)

1. Simulation layers where visible in all time periods.

2. Zooming in and out of the charts didn't adjust the candle time period and / or size....

I don't know if it may be reproduced or how. Just documenting the occurrence.

**Comment by Luis-Fernando-Molina** [comment]
When it happens again capture the browser console errors

**Comment by Luis-Fernando-Molina** [comment]
@julian-molina did this happened again? I guess no because you didnt captured the browser console messages.

**Comment by julian-molina** [comment]
Hasn't happened again...
