### ISSUE TITLE
Changing the name of a session after starting it turns it unresponsive

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#66]
If you change the name of a testing session once the corresponding process is already running, the session will become unresponsive. It will not react to the Run command.

If you change the name of a testing session once it is running, it will also become unresponsive.

**Comment by Luis-Fernando-Molina** [comment]
This is by desing. The name of the session is part of what defines a session within that process. Once a process is started it gets attached to that session and if you change the name without restarting the process you will get this situation. Just restart the process if you change the name and everything will be allright.
