### ISSUE TITLE
Error with USDT_BTC.json file on Storage on Version Alpha release 0.0.3-alpha

### ISSUE THREAD

**Issue by gabrielacosta** [Superalgos/DesktopApp#78]
Hi, 

First, thanks for the hard work. 
Secondly, I was testing the version alpha 0.0.0.3 alpha.

![image](https://user-images.githubusercontent.com/8519425/67386641-14632780-f5e1-11e9-821a-b3c2e8cba73c.png)

I was following the procedure presented for the latest release.

![image](https://user-images.githubusercontent.com/8519425/67386693-2b097e80-f5e1-11e9-8df3-a4f5ef234b33.png)

When I click on Run the Task.  I opened the Console on Chrome and found the following error related with the base data from JSON. 

![image](https://user-images.githubusercontent.com/8519425/67386790-59875980-f5e1-11e9-9d48-0a12b7256aed.png)

If I click on the error on Chrome. I got redirected to 

![image](https://user-images.githubusercontent.com/8519425/67387003-bc78f080-f5e1-11e9-8234-2d47df437500.png)

Then, after a few minutes I decided to stop the Task and see the results. 

When I change the the designer view and click on the layers for the BCK Test 2019. 

I got another set of errors. 

![image](https://user-images.githubusercontent.com/8519425/67386923-95222380-f5e1-11e9-9b8c-44f1ee36a3c2.png)

I was speaking on parallel with Julian and he recommended the following procedure to remove the possible error. 

Remove the folder with the AAJason (as presented on the next image) and retry the backtest. 

![image](https://user-images.githubusercontent.com/8519425/67387245-38733880-f5e2-11e9-966b-2e0609d5d17e.png)

The Issue could be due to the previous version of the alpha application, that I was testing 0.0.3.14. It could create some unexpected changes on the application folder.

I will try the recommended procedure and report the results. 

Kind regards, 

Gabriel

**Comment by Luis-Fernando-Molina** [comment]
Hi Gabriel,

There are still few situation in which the UI is looking for files that might not exist. That will be solved in future releases. This should not prevent the App to work fine. Is there anything that you believe is not working as expected?

**Comment by Luis-Fernando-Molina** [comment]
A new specific issue was created for the files being requested and not found.

https://github.com/Superalgos/DesktopApp/issues/101
