### ISSUE TITLE
OS crash or auto-system restart damages data

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#79]
When data is damaged, the app becomes unusable. In this case, the charts are not loading due to errors in the data:

![image](https://user-images.githubusercontent.com/13994516/67464868-61c4b080-f644-11e9-97d2-c40836cd0397.png)

This is what the browser's console shows:

![image](https://user-images.githubusercontent.com/13994516/67464818-4c4f8680-f644-11e9-9777-4be62e3879fd.png)

It seems like several files were damaged due to forcefully closing the app during a restart.

We need either more resilience in those cases, or at least a workaround to not have to redeploy the latest release data, which puts the user out of business for at least 6 hours (download, unpack and catching up to present time).

**Comment by Luis-Fernando-Molina** [comment]
Did you try to run the process of those indicators again to see if they fix the damaged files?

**Comment by Luis-Fernando-Molina** [comment]
@julian-molina report please if this happened again

**Comment by Luis-Fernando-Molina** [comment]
No answer closing this issue.
