### ISSUE TITLE
Conditions layer is not working on a live trading session

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#81]
When you turn the layer on, it doesn't seem to interact with the conditions and rules in the designer.

**Comment by Luis-Fernando-Molina** [comment]
Is it reproducible or happened once?

**Comment by julian-molina** [comment]
It doesn't work on either of the virtual machines

**Comment by julian-molina** [comment]
Actually, none of the simulation layers are working when on a live session. It is reproducible.

**Comment by Luis-Fernando-Molina** [comment]
This issue has too little info to work with. Have you check the browser console for messages there? When you say it is not working, what do you mean? You do not see the plots of those layers? @julian-molina

**Comment by julian-molina** [comment]
To reproduce it, start a live trading session of WHB and let it run a bit. Then activate the Simulation Conditions layer. Move the mouse pointer over the latest candle and you will see no conditions are highlighted. Of course, it is a lot more clear if you know which conditions should be highlighted and a single candle may not activate any conditions, so you can add an obvious one.

I haven't tested on the latest versions of the app, only on the release version.

I can't see any errors on the browser's console.

**Comment by Luis-Fernando-Molina** [comment]
The issue is not reproducible.

I setup live session (that was not up to date) and let it run for a few hours and then got this:

![image](https://user-images.githubusercontent.com/9479367/69901504-eb257c00-1382-11ea-891d-2cdb8eac84d2.png)
