### ISSUE TITLE
Trigger on conditions met but strategy is not triggered

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#82]
Using Bull Run Rider release version, on October 25th between 11 and 19 hours, the trigger on event conditions are met en each of the candles in the time range. However, the strategy was not triggered in a backtest and was not triggered on the VM trading live.

![image](https://user-images.githubusercontent.com/13994516/67619085-5a91d400-f7f7-11e9-9db6-825d99d74a92.png)

I'm attaching logs from the backtesting session:

[Loop.00000002.0000.txt](https://github.com/Superalgos/DesktopApp/files/3774778/Loop.00000002.0000.txt)

The concerned candles seem to be processed normally:

![image](https://user-images.githubusercontent.com/13994516/67619041-e9522100-f7f6-11e9-9358-6e2eb83b2d2b.png)

Workspace:

[Share - Workspace - Bull run rider - USDT- SDA v.0.0.3.txt](https://github.com/Superalgos/DesktopApp/files/3774780/Share.-.Workspace.-.Bull.run.rider.-.USDT-.SDA.v.0.0.3.txt)

**Comment by julian-molina** [comment]
UPDATE:

I run a new backtest, this time with the latest version of the app V0.0.4.1.

To my surprise, the trigger on event that was ignored before, is now acknowledged. 
However, there is a new event closer to the present time that is ignored, again:

![image](https://user-images.githubusercontent.com/13994516/67639271-35cc5800-f8ee-11e9-8b6e-66ce6fbeed68.png)

**Comment by Luis-Fernando-Molina** [comment]
@julian-molina can you please check if this still happens with the current version and post the workspace that works in the current version and instruction of how to reproduce it?

**Comment by julian-molina** [comment]
I have reproduced the issue with the latest version of the app.

1. Workspace: 
[Backup - Workspace - V5 - BRR - WHB.txt](https://github.com/Superalgos/DesktopApp/files/3862881/Backup.-.Workspace.-.V5.-.BRR.-.WHB.txt)

2. Run Backtest BRR as is.

3. See how trigger on conditions are met, but strategy is not triggered.
![Test](https://user-images.githubusercontent.com/13994516/69132946-559e0880-0ab5-11ea-9bdc-7c6f7f9d23f6.gif)

4. Modify Backtest BRR final date to a few days in the future, and the strategy is triggered where it wasn't triggered before.

**Comment by Luis-Fernando-Molina** [comment]
I am already at the next version, will need you to update this.

**Comment by Luis-Fernando-Molina** [comment]
There was a problem with strategies that had not closed yet and was fixed. Strategies that are still triggered on at the head of the market will look like this at the plotter:

![image](https://user-images.githubusercontent.com/9479367/69655414-c1184500-1076-11ea-9ec3-deaed2a6393a.png)

**Comment by Luis-Fernando-Molina** [comment]
By the way, I also fixed how open positions look at the plotter:

![image](https://user-images.githubusercontent.com/9479367/69657694-12c2ce80-107b-11ea-84c7-0c9d8ff28bba.png)
