### ISSUE TITLE
Failures in trades at 00:00:00hs

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/DesktopApp#83]
There is some problems  at time 00hs when a trend is running. This has happened only in few occasions. I attached videos and workspace.
Video 1: at the end of the trade the ROI changes twice.
Video 2: the trade ends abruptly

[Archive.zip](https://github.com/Superalgos/DesktopApp/files/3774953/Archive.zip)

.

**Comment by Luis-Fernando-Molina** [comment]
@EduRemix to check this I would need to know if this is still happening at the latest version provided, and if yes, a workspace that is being used. Also instructions on which task to execute and at which date and time period this happens.

**Comment by Luis-Fernando-Molina** [comment]
No answer, closing this issue.
