### ISSUE TITLE
Announcements - basic variables in zero or undefined

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#86]
The following formula would make sense for announcements at the take position event:

```
"Selling BTC at " + candle.close + " with stop at " + stopLoss + " and TP target at " +  takeProfit
```

Currently, both stopLoss and takeProfit return 0.

I tried using positionRate instead of candle.close, but is undefined.

**Comment by Luis-Fernando-Molina** [comment]
This was fixed. Process will not be terminated now. Only a warning at the logs will appear.

![image](https://user-images.githubusercontent.com/9479367/69343975-e10ec980-0c6e-11ea-8959-4d2551781edb.png)

**Comment by Luis-Fernando-Molina** [comment]
Last comment was intended for another issue

**Comment by Luis-Fernando-Molina** [comment]
This was fixed. 

![image](https://user-images.githubusercontent.com/9479367/69549567-cfdcfa00-0f99-11ea-9922-517d79e35844.png)
