### ISSUE TITLE
Announcements - Too many requests to Telegram, the task stops

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#87]
There seems to be an unhandled error when there are too many requests to Telegram.

![image](https://user-images.githubusercontent.com/13994516/68238234-0bbf1800-0009-11ea-9413-caf138304636.png)

**Comment by Luis-Fernando-Molina** [comment]
This was fixed. Process will not be terminated now. Only a warning at the logs will appear.
![image](https://user-images.githubusercontent.com/9479367/69344130-2af7af80-0c6f-11ea-8d21-07bbf0046048.png)
