### ISSUE TITLE
Configurable keyboard shortcuts switch from CTRL to CTRL + ALT

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#89]
We need to change the key sequence for creating keyboard shortcuts to avoid key combinations already taken by Chrome. Changing <kbd>CTRL</kbd> for <kbd>CTRL</kbd> + <kbd>ALT</kbd> solves the issue completely.

**Comment by julian-molina** [comment]
For the sake of clarity, navigation via keyboard should remain as is, using only <kbd>CTRL</kbd> plus arrow keys.

**Comment by Luis-Fernando-Molina** [comment]
This is done. You can still use shift key for upper case shorcut keys, expanding the possible combinations to all lower case and upper case letters.
