### ISSUE TITLE
Condition falsely evaluates true in WHB Strategy 

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/DesktopApp#93]
Last version Superalgos-Desktop-App V 0 0 5 4

WHB Strategy 1hs -> Take position -> Situation 1 -> Condition 5 -> always true

**Comment by julian-molina** [comment]
You may use the following workspace for testing purposes:

[Backup - Workspace - V5 - BRR - WHB.txt](https://github.com/Superalgos/DesktopApp/files/3865471/Backup.-.Workspace.-.V5.-.BRR.-.WHB.txt)

**Comment by Luis-Fernando-Molina** [comment]
This needs to be re tested in the latest version

**Comment by Luis-Fernando-Molina** [comment]
@EduRemix @julian-molina check if this still happens on the latest version provided

**Comment by Luis-Fernando-Molina** [comment]
> WHB Strategy 1hs -> Take position -> Situation 1 -> Condition 5 -> always true

This could not be reproduced, and nothing wrong was seen on other conditions as well. Next time provide and exact way of reproducing the behavior.

**Comment by Luis-Fernando-Molina** [comment]
```
chart.at01hs.bollingerSubChannel.slope != "Extreme" || 
(
    chart.at01hs.bollingerSubChannel.period <=6 && 
    chart.at08hs.bollingerChannel.direction === "Down" && 
    chart.at06hs.bollingerChannel.direction === "Down"  && 
    chart.at04hs.bollingerChannel.direction === "Down" && 
    chart.at02hs.bollingerSubChannel.slope === ("Extreme" || "Steep")
)

```

This was the condition code. If you have doubts on the behavior, next time break down that complex logic in multiple individual conditions to see which one is evaluating to true and false individually.
