### ISSUE TITLE
Discontinue keyboard shortcut rejections

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#94]
Currently, when you attempt to set a keyboard shortcut and the key combination of choice is already being used, the operation is prevented, with a notice letting the user know the key combination is in use.

In my view, the app should allow the user to easily override previously set shortcuts.

The ideal case scenario would be that after the notice, the user was able to chose either to proceed setting the new shortcut or not. For example, if the user hits the key combination again while the notice is visible, then the new shortcut is established and the old one discarded.

**Comment by julian-molina** [comment]
Also, it would be good to have numbers available. At the moment, the app does not react when trying to set up a shortcut with number keys from 0 to 9.

**Comment by Luis-Fernando-Molina** [comment]
Done.
