### ISSUE TITLE
Discontinue "repo" attribute in bot's configuration

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#95]
Current config of Paula:

{
"codeName": "AAPaula",
"repo": "AAPaula-Indicator-Bot"
}

**Comment by Luis-Fernando-Molina** [comment]
@julian-molina this was done.

Currently only indicator and sensor bots that are still not defined at the UI and their code and config needs to be laoded from a file need the repo definition at the Bot Instance internal settings as the only needed setting to specify there.

The internal settings of the Process Instances are not needed anymore for any bot no matter if they are defined at the UI or not.
