### ISSUE TITLE
Children to inherit parent properties upon creation

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/DesktopApp#99]
It'd be very useful if children created from a parent object were created with the same properties. In my case, my main interest is the *tensor* property.

For example, in the context of building an indicator, I create a *record definition* element and I need to define lots of *record properties*. In the current state, I can quickly create 15 properties, but then it takes minutes to chase around the properties to apply the tensor and it is fundamental to do it. Then I have to create the 15 formulas and again apply the tensor to each of them.

**Comment by Luis-Fernando-Molina** [comment]
Done, it now inherits all the current 4 possible properties:

isPinned, isFrozen, isCollapsed and isTensed
